using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace ubank
{
    public partial class Activity_detail : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

            String id = Session["id"].ToString();
            decimal dec = System.Convert.ToDecimal(id);


        }




        protected void LinkButton1_Click(object sender, EventArgs e)
        {
            String id = Session["id"].ToString();
            decimal dec = System.Convert.ToDecimal(id);

            string struserid = Session["UserID"].ToString();

            Session["check"] = 1;
            Session["subject"] = "complaint";
            Session["subject"] = "complaint";
            Session["to"] = "hh";
            Session["date"] = DateTime.Now.ToString();
            Session["channel"] = "";
            Session["problem"] = "";
            Session["system"] = "";
            Session["module"] = "";
            int actvity_id = System.Convert.ToInt16(activity.SelectedItem.Value);
            string des = TextBox1.Text;
            string time = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

            databaseDataContext data = new databaseDataContext();


            RefActivityDetail obj = new RefActivityDetail
            {


                complaint_id = dec,
                ActivityID = actvity_id,
                Activity_description = des,
                Activity_time = System.Convert.ToDateTime(time),
                Activity_performed_by = struserid

            };
            data.RefActivityDetails.InsertOnSubmit(obj);

            RefComplaint obj11 = data.RefComplaints.Single(c => c.complaint_id.Equals(dec));



            if (actvity_id.Equals(2) || actvity_id.Equals(10) || actvity_id.Equals(12))
            {

                obj11.status = "Close";
            }
            else
            {
                obj11.status = "Open";
            }






            obj11.ActivityID = actvity_id;
            obj11.Assigne_to = struserid;
            data.SubmitChanges();




            SendEmail();

        }



        public void SendEmail()
        {

            String id = Session["id"].ToString();
            decimal dec = System.Convert.ToDecimal(id);
            string struserid = Session["UserID"].ToString();

            databaseDataContext data = new databaseDataContext();

            var complaint = (from u in data.RefComplaints
                             where u.complaint_id.Equals(dec)
                             select u).FirstOrDefault();

            String assigne_by = complaint.Reporters_email.ToString();


            String subject = complaint.subject + " " + complaint.category + " ( ID: " + complaint.complaint_id.ToString() + " )";

            //  String bodyforemail =  + "\n\n" + ;



            //var email_to = (from u in data.UserManagers
            //            where u.UserID.Equals()
            //            select u).FirstOrDefault();

            var email_from = (from u in data.UserManagers
                              where u.UserID.Equals(struserid)
                              select u).FirstOrDefault();

            Session["subject"] = subject;
            Session["date"] = complaint.date;
            Session["from"] = email_from.OrgEmail;
            Session["to"] = "IT Help Desk";
            Session["channel"] = complaint.Reported_channel_ID;
            Session["problem"] = complaint.Reported_problem_ID;
            Session["system"] = complaint.subject;
            Session["module"] = complaint.category;



            MailMessage message = new System.Net.Mail.MailMessage();
            message.To.Add("ashi.iram@ubank.com.pk");
            //  message.To.Add(email_to.OrgEmail);
            message.CC.Add(email_from.OrgEmail);
            message.Subject = subject;
            message.From = new System.Net.Mail.MailAddress("webportal@ubank.com.pk");
            //message.Body = bodyforemail;
            message.Body = "Dear Ashi Irum" + "\n The issue of " + complaint.category + " module of " + complaint.subject + " created on  DATE: " + complaint.date.ToString() + " .\n"
                            + email_from.UserName + " is resolving the complaint which is generated by You.\n\n Problem Status : " + activity.SelectedItem.Text + "\n " + TextBox1.Text + ".\n Kindly check and confirm.\n\n Thank you & Regards \n UBank \n\n\n This Email is Auto-Generated by Ubank Support Incident Record Portal."
                            + "\n Following are the steps to view the pending tasks that are posted in your account " + "\n1.  Open website http://localhost:2045/Default.aspx \n 2.  Logon to the website \n 3.  Click on Action Register \n 4.  Click on Update Request Status \n\n If you don’t have rights, please contact Web administrator";
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient(ConfigurationManager.AppSettings["smtpServer"].ToString());
            smtp.Send(message);

            Response.Redirect("validation_resolve.aspx");

            //return true;
        }









    }
}